# Generated by Django 4.2.4 on 2023-08-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_district_rename_city_branch_alter_branch_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
